# Scheme for configuration files of the CiviCRM theme module.

civicrmtheme.settings:
  type: config_object
  label: 'CiviCRM theme settings'
  mapping:
    admin_theme:
      type: string
      label: 'Administration theme'
    public_theme:
      type: string
      label: 'Public theme'